### ISSUE TITLE
Command 'CodeSnap 📸' resulted in an error (panel.postMessage is not a function)

### ISSUE THREAD

**Issue by NatoBoram** [kufii/CodeSnap#46]
```yaml
Version: 1.49.0-insider
Commit: b6d4fec3714ff897f72c1dab8cc02b7421a8f131
Date: 2020-09-01T05:54:42.740Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by teuscard** [comment]
It also stopped working for me after VS Code's last update.

**Comment by kufii** [comment]
Hmm ok, I'll try to fix this tomorrow

**Comment by gfazioli** [comment]
same for me on Mac. Stopped to work with `August 2020 (version 1.49)` of Visual Studio

**Comment by kufii** [comment]
I'm having trouble running any extensions on the newest version at all, I opened an issue on vscode repo

https://github.com/microsoft/vscode/issues/106504

hopefully I can get it resolved soon

**Comment by teuscard** [comment]
> I'm having trouble running any extensions on the newest version at all, I opened an issue on vscode repo
> 
> [microsoft/vscode#106504](https://github.com/microsoft/vscode/issues/106504)
> 
> hopefully I can get it resolved soon

We're looking forward to it. Thank you for making this awesome extension.

**Comment by teuscard** [comment]
> I'm having trouble running any extensions on the newest version at all, I opened an issue on vscode repo
> 
> [microsoft/vscode#106504](https://github.com/microsoft/vscode/issues/106504)
> 
> hopefully I can get it resolved soon

We're looking forward to it. Thank you for developing this awesome extension.

**Comment by kufii** [comment]
Issue resolved and new release pushed

**Comment by ManuelFlorez** [comment]
thanks you!
